<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-11T22:15:27 IST" name="Default suite" finished-at="2024-12-11T22:15:32 IST" duration-ms="4346">
    <groups>
    </groups>
    <test started-at="2024-12-11T22:15:27 IST" name="Default test" finished-at="2024-12-11T22:15:32 IST" duration-ms="4346">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:tests.LoginTest@503d687a]" started-at="2024-12-11T22:15:27 IST" name="beforeClass" finished-at="2024-12-11T22:15:30 IST" duration-ms="2320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="tc01_loginSucceed()[pri:0, instance:tests.LoginTest@503d687a]" started-at="2024-12-11T22:15:30 IST" name="tc01_loginSucceed" finished-at="2024-12-11T22:15:31 IST" duration-ms="1269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01_loginSucceed -->
        <test-method signature="tc02_loginFailed()[pri:0, instance:tests.LoginTest@503d687a]" started-at="2024-12-11T22:15:31 IST" name="tc02_loginFailed" finished-at="2024-12-11T22:15:31 IST" duration-ms="504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc02_loginFailed -->
        <test-method signature="tc03_loginFailed_empty()[pri:0, instance:tests.LoginTest@503d687a]" started-at="2024-12-11T22:15:31 IST" name="tc03_loginFailed_empty" finished-at="2024-12-11T22:15:32 IST" duration-ms="212" status="FAIL">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...is required> but was:<...and password do not match any user in this service>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...is required> but was:<...and password do not match any user in this service>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at tests.LoginTest.tc03_loginFailed_empty(LoginTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc03_loginFailed_empty -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:tests.LoginTest@503d687a]" started-at="2024-12-11T22:15:32 IST" name="afterClass" finished-at="2024-12-11T22:15:32 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
